# Generated by Django 3.0.2 on 2020-06-11 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Browser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=8192)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('platform', models.CharField(blank=True, default='', max_length=8192)),
                ('code_name', models.CharField(blank=True, default='', max_length=8192)),
                ('name', models.CharField(blank=True, default='', max_length=8192)),
                ('version', models.CharField(blank=True, default='', max_length=8192)),
                ('language', models.CharField(blank=True, default='', max_length=8192)),
                ('user_agent', models.CharField(blank=True, default='', max_length=8192)),
                ('timezone', models.CharField(blank=True, default='', max_length=8192)),
                ('iso_timestamps', models.CharField(blank=True, default='', max_length=8192)),
                ('cookies_enabled', models.BooleanField(default=False)),
                ('screen_width', models.IntegerField(blank=True, default=0)),
                ('screen_height', models.IntegerField(blank=True, default=0)),
                ('screen_color_depth', models.IntegerField(blank=True, default=0)),
                ('screen_pixel_depth', models.IntegerField(blank=True, default=0)),
                ('screen_available_height', models.IntegerField(blank=True, default=0)),
                ('screen_available_width', models.IntegerField(blank=True, default=0)),
                ('viewport_height', models.IntegerField(blank=True, default=0)),
                ('viewport_width', models.IntegerField(blank=True, default=0)),
                ('luxon_intl', models.BooleanField(default=False)),
                ('luxon_intl_tokens', models.BooleanField(default=False)),
                ('luxon_zones', models.BooleanField(default=False)),
                ('luxon_relative', models.BooleanField(default=False)),
            ],
        ),
    ]
