# Generated by Django 3.0.2 on 2020-06-11 18:11

from django.db import migrations
import fenicemisc.fields


class Migration(migrations.Migration):

    dependencies = [
        ('fenicegdpr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gdprpolicy',
            name='text',
            field=fenicemisc.fields.CleanHtmlRichTextField(),
        ),
    ]
