# Generated by Django 3.0.2 on 2020-06-11 17:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import fenicemisc.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1024, unique=True)),
                ('content', fenicemisc.fields.CleanHtmlRichTextUploadingField()),
                ('publishing_date', models.DateTimeField()),
                ('visible', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='article_created_set', to=settings.AUTH_USER_MODEL)),
                ('last_modified_by', models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='article_edited_set', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
