# Generated by Django 3.0.2 on 2020-06-11 17:31

from django.db import migrations, models
import django.db.models.deletion
import fenicemisc.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OpenLicense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=512, unique=True)),
                ('long_name', models.CharField(max_length=4096)),
                ('url', models.URLField(blank=True, default='', max_length=4096)),
            ],
        ),
        migrations.CreateModel(
            name='OpenImageCredit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumb_path', models.FilePathField(max_length=4096, path=fenicemisc.models.openimagecredit_image_path, unique=True)),
                ('title', models.CharField(blank=True, default='', max_length=4096)),
                ('description', models.CharField(blank=True, default='', max_length=4096)),
                ('author', models.CharField(blank=True, default='', max_length=4096)),
                ('url', models.URLField(blank=True, default='', max_length=4096)),
                ('license', models.ForeignKey(blank=True, default=fenicemisc.models.get_default_open_license, on_delete=django.db.models.deletion.PROTECT, to='fenicemisc.OpenLicense')),
            ],
        ),
    ]
